# Generated by Django 5.2.17 on 2026-09-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='grinder.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='grinder.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('duration_seconds__isnull', True), ('ended_at__isnull', True), ('started_at__isnull', False)), fields=('user',), name='one_running_action_per_user'), models.CheckConstraint(condition=models.Q(models.Q(('duration_seconds__isnull', True), ('ended_at__isnull', True), ('started_at__isnull', False)), models.Q(('duration_seconds__isnull', False), ('ended_at__isnull', True), ('started_at__isnull', True)), models.Q(('duration_seconds__isnull', False), ('ended_at__isnull', False), ('started_at__isnull', False)), _connector='OR'), name='action_has_valid_time_state'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='action_ends_after_start'), models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gt', 0), _connector='OR'), name='action_duration_positive')],
            },
        ),
    ]
